
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int palRes_sint = 9;
  public static final int opAsig_tepr = 26;
  public static final int opRel_men = 40;
  public static final int opArt_suma = 50;
  public static final int rango = 25;
  public static final int palRes_ig = 8;
  public static final int tipoDato_al = 16;
  public static final int macro_c = 20;
  public static final int palRes_inic = 11;
  public static final int tipoDato_pr = 17;
  public static final int llave_c = 36;
  public static final int palRes_lex = 5;
  public static final int coma = 59;
  public static final int llave_a = 35;
  public static final int opRel_may = 39;
  public static final int sigExcl_c = 44;
  public static final int caracter = 28;
  public static final int palRes_ter = 7;
  public static final int palRes_dec = 6;
  public static final int palRes_semant = 13;
  public static final int opAgr_c = 56;
  public static final int sigExcl_a = 43;
  public static final int opAgr_a = 55;
  public static final int dos_puntos = 37;
  public static final int produc = 30;
  public static final int Terminal = 29;
  public static final int sentCont_sn = 22;
  public static final int numero = 32;
  public static final int sentCont_si = 21;
  public static final int EOF = 0;
  public static final int punto_coma = 38;
  public static final int ident = 31;
  public static final int error = 1;
  public static final int tipoDato_cd = 18;
  public static final int barra = 58;
  public static final int palRes_prod = 12;
  public static final int barra_inv = 57;
  public static final int punto = 60;
  public static final int opRel_ig = 41;
  public static final int opLog_y = 54;
  public static final int opAsig = 45;
  public static final int palRes_user = 3;
  public static final int palRes_nter = 10;
  public static final int tipoDato_ex = 15;
  public static final int comi_dob = 48;
  public static final int opArt_resta = 49;
  public static final int sigPeso = 47;
  public static final int expReg = 4;
  public static final int opLog_o = 53;
  public static final int opArt_mult = 52;
  public static final int macro_ls = 19;
  public static final int comi_sim = 46;
  public static final int funcion_tk = 24;
  public static final int SYMBOL = 61;
  public static final int opArt_pot = 51;
  public static final int opRel_dif = 42;
  public static final int funcion_nc = 23;
  public static final int corchete_c = 34;
  public static final int corchete_a = 33;
  public static final int opAsig_cad = 27;
  public static final int cadena = 2;
  public static final int palRes_imp = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cadena",
  "palRes_user",
  "expReg",
  "palRes_lex",
  "palRes_dec",
  "palRes_ter",
  "palRes_ig",
  "palRes_sint",
  "palRes_nter",
  "palRes_inic",
  "palRes_prod",
  "palRes_semant",
  "palRes_imp",
  "tipoDato_ex",
  "tipoDato_al",
  "tipoDato_pr",
  "tipoDato_cd",
  "macro_ls",
  "macro_c",
  "sentCont_si",
  "sentCont_sn",
  "funcion_nc",
  "funcion_tk",
  "rango",
  "opAsig_tepr",
  "opAsig_cad",
  "caracter",
  "Terminal",
  "produc",
  "ident",
  "numero",
  "corchete_a",
  "corchete_c",
  "llave_a",
  "llave_c",
  "dos_puntos",
  "punto_coma",
  "opRel_may",
  "opRel_men",
  "opRel_ig",
  "opRel_dif",
  "sigExcl_a",
  "sigExcl_c",
  "opAsig",
  "comi_sim",
  "sigPeso",
  "comi_dob",
  "opArt_resta",
  "opArt_suma",
  "opArt_pot",
  "opArt_mult",
  "opLog_o",
  "opLog_y",
  "opAgr_a",
  "opAgr_c",
  "barra_inv",
  "barra",
  "coma",
  "punto",
  "SYMBOL"
  };
}

